development:
  accessLevel:
  - public
  id: proxy.Public.Stanford
  wms: http://localhost:8983/geoserver/wms
  admin_url: http://localhost:8983/geoserver/rest
  admin_pass: geoserver 
  admin_user: admin
test:
  accessLevel:
  - public
  id: proxy.Public.Stanford
  wms: http://localhost:8983/geoserver/wms
  admin_url: http://localhost:8983/geoserver/rest
  admin_pass: geoserver 
  admin_user: admin
production:
  accessLevel:
  - public
  id: proxy.Public.Stanford
  wms: http://localhost:8983/geoserver/wms
  admin_url: http://localhost:8983/geoserver/rest
  admin_pass: geoserver 
  admin_user: admin
